version: "3.8"

services:
  web_reipel:
    image: nivaldeir/reipel:v1
    ports:
      - 3000:3000
    shm_size: '1gb'
    volumes:
      - web_reipel_data:/data
    environment:
      - DATABASE_URL="file:./dev.db"
      - api_token="eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNjVmOWU0MGJlMmQ5NjYwMDY5ZTk0ZDFkIiwiaWF0IjoxNzEwODc1NjU5fQ.TLZ7YYSK_5EuJT9-8iPAUsCFTmnPCiLcJD0ujPYy0tU"
      - BCRYPT_ROUND=12
      - NEXTAUTH_SECRET=98E3B2CC28F61492C6934531C828C
      - IP_CALLISTOR=25.57.82.40
volumes:
  web_reipel_data:
